### ISSUE TITLE
What are the system requirements and the version of mediaviki?

### ISSUE THREAD

**Issue by kubanezru** [Ichinya/yandex_turbo_for_mediawiki#3]
А какая версия должна быть у mediawiki и что должно быть установлено? Попробовал на старой 1.30.0 и на чистой 1.35.1: генерирует 6кб cache.db, а сама ругается: 

`Fatal error: Uncaught TypeError: Return value of cContent::getContent() must be of the type array, null returned in /home/sites/htdocs/mediawikiupdate/turbo/libs/cContent.php:47 Stack trace: #0 /home/sites/htdocs/mediawikiupdate/turbo/libs/cContent.php(57): cContent->getContent() #1 /home/sites/htdocs/mediawikiupdate/turbo/libs/cPageList.php(27): cContent->getContentAll() #2 /home/sites/htdocs/mediawikiupdate/turbo/index.php(28): cPageList->init() #3 {main} thrown in /home/sites/htdocs/mediawikiupdate/turbo/libs/cContent.php on line 47`

Стоит Ubuntu 16.04 с PHP 7.4.18 (fpm-fcgi) и nginx. Доставил sqlite.

![cache_db](https://user-images.githubusercontent.com/40037340/118092176-6989a880-b3d4-11eb-8a3e-ad580b087c43.png)

**Comment by ichinya** [comment]
При запуске создается файл `config.inc.php`. В нем, в самом начале поменяйте
`$server = $_SERVER['HTTP_HOST'];`
на свой сайт, например,
`$server = 'mediawiki.com';`

Ну и ниже 
`'here' => $server . $_SERVER['REQUEST_URI'],`
на
`'here' => $server . "/turbo/",`

Судя по ошибкам возможные проблемы:
с htaccess и чпу 
нет доступа к API

**Comment by ichinya** [comment]
также попробуйте зайти по адресу [mediawiki](https://www.mediawiki.org/w/api.php)
т.е. у Вас должно быть `https://сайт-вики/api.php`
