### ISSUE TITLE
I have an error.

### ISSUE THREAD

**Issue by artemsnite** [Ichinya/yandex_turbo_for_mediawiki#6]
Error: `Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/u1005435/data/www/artemscraft.ru/wiki/libs/cPageList.php on line 5`
If i need something to attach, please answer me. Thank you. 
_со мной можно по-русски если что)_

**Comment by ichinya** [comment]
Судя по всему, проблема в версии PHP. Минимально допустимая 7.4. Скоро буду переписывать, чтобы немного оптимизировать. Там уже буду переделывать на PHP8

**Comment by Artemsnite** [comment]
ок спасибо

**Comment by artemsnite** [comment]
Я поменял на  php 7.4 и теперь вижу вот это:
![Screenshot_20220130-090924_Chrome](https://user-images.githubusercontent.com/96045967/151688838-c60e4503-e044-4f2b-a48c-711fd5eb8293.png)

**Comment by ichinya** [comment]
это только дополнение, а не сам движок. Его нужно разместить в папке с движком Mediawiki. А дополнение просто подключается к нему через api.
![image](https://user-images.githubusercontent.com/3314686/151690257-a8df2dd2-d05f-4247-8f7b-0c95241a0e92.png)

В теории, если в `config.inc.php` указать в переменной $server адрес, где находится mediawiki, то должно тоже работать.

То есть должен быть открыт файл https://site.ru/api.php , т.е. в переменную $server нужно указать https://site.ru/

**Comment by artemsnite** [comment]
я сделал как вы написали, но результат тот же
config.inc.php :
`<?php
$server = 'wiki.artemscraft.ru';
return [
    'defaultDate' => 1606780800, // 2020.12.01 00:00
    'debug' => false,
    'server' => $server,
    'here' => $server . '/turbo/',
    // урл API wiki
    'urlAPI' => $server . "/api.php",
    // если не найден автор статьи, то будет подставляться этот
    'defaultAuthor' => 'Admin',
    // меняет авторов статей на defaultAuthor
    'replaceAuthor' => false,
    // шаблон по-умолчанию
    'defaultTemplate' => 'turbo',
    // электронный ящик для сообщений
    'email' => ''
];`

**Comment by artemsnite** [comment]
решение нашел, спасибо вам за помощь!

**Comment by ichinya** [comment]
генерация ссылок работает немного криво.
Попробуйте в переменную $server написать адрес с http. То есть так 
``` $server = 'https://wiki.artemscraft.ru/'```
Ну или вернуть по умолчанию
