### ISSUE TITLE
Не могу завести скрипт

### ISSUE THREAD

**Issue by Valirius** [Ichinya/yandex_turbo_for_mediawiki#7]
MW 1.39.5
Скрипт я так понял 1.3.1 - последний короч

Что делал
1. Залил за хостинг
![01](https://github.com/Ichinya/yandex_turbo_for_mediawiki/assets/22143019/e1ffbba4-e2ef-4e09-a15b-725b4ef27809)

2. Настройки оставил по дефолту:
![03](https://github.com/Ichinya/yandex_turbo_for_mediawiki/assets/22143019/8092b2c4-7e46-481c-99de-139861618f69)

3. Получаю ошибку о невозможности подцепиться к API или отсутствии статей
![02](https://github.com/Ichinya/yandex_turbo_for_mediawiki/assets/22143019/bf8af1d0-5889-4828-a48f-4eb57d3dba5f)

В конфие MW ничего не менял. Но https://wiki.treneron.ru/api.php вроде открывается. 
Не знаю показатель ли это подключенного АПИ))

Страниц в вики полно. Должно хватать для работы скрипта вроде как

**Comment by ichinya** [comment]
Хм, сейчас попробовал перейти, действительно какой то косяк. По идее всё должно работать нормально. Сейчас гляну

**Comment by ichinya** [comment]
Можно просто указать в конфиге 
```php
<?php
$server = $_SERVER['HTTP_HOST'];
return [
    'defaultDate' => 1606780800, // 2020.12.01 00:00
    'debug' => false,
    'server' => $server,
    'here' => $server . $_SERVER['REQUEST_URI'],
    'urlAPI' => "https://wiki.treneron.ru/api.php", // <--- ВОТ ТУТ ПРОСТО УКАЗАТЬ НУЖНЫЙ АДРЕС
    'defaultAuthor' => 'Admin',
    'replaceAuthor' => false,
    'defaultTemplate' => 'turbo',
    'email' => ''
];
```

При первом переходе будет "скачивание" всех страниц, это своего рода кеширование, потом при добавлении новых страниц будет просто добавляться новые страницы в кеш и задержек уже не должно быть
