### ISSUE TITLE
500 error, ошибка в cPage.php

### ISSUE THREAD

**Issue by Valirius** [Ichinya/yandex_turbo_for_mediawiki#8]
Привет. Не понятно что с ним) Не заводится. На шареде заводился вроде, на серваке не хочет.

Сначала дает вот такое
```
[Wed Aug 07 16:00:05.745195 2024] [php:warn] [pid 67670] [client 109.252.75.170:41752] PHP Warning:  Undefined array key "init" in /var/www/fastuser/data/www/wiki.site.ru/turbo/libs/cDB.php on line 100
```

Там он имя подтягивает я так понял. Правда не понятно какое))
        return self::$config[$name];

А следом через пару миллисекунд вот это
```
[Wed Aug 07 16:00:05.745454 2024] [php:error] [pid 67193] [client 109.252.75.170:56130] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property cPage::$url of type string in /var/www/fastuser/data/www/wiki.site.ru/turbo/libs/cPage.php:27\n
Stack trace:\n
#0 /var/www/fastuser/data/www/wiki.site.ru/turbo/libs/cPageList.php(110): cPage::convertArrayToPage()\n
#1 /var/www/fastuser/data/www/wiki.site.ru/turbo/libs/cPageList.php(80): cPageList->convertArrayToPage()\n
#2 /var/www/fastuser/data/www/wiki.site.ru/turbo/index.php(35): cPageList->getPageId()\n
#3 {main}\n  thrown in /var/www/fastuser/data/www/wiki.site.ru/turbo/libs/cPage.php on line 27
```

Там на 27ой строке вот это
        $page->url = $pageDB['url'];

Причем похоже он кеш тоже не создает. Где-то ошибается. Ибо кэш всего 32 килобайта. Хотя должен быть побольше по идее) По крайней мере на шареде до удаления был 2 Мб.

**Comment by ichinya** [comment]
Доброго дня. Напишите немного больше информации:
1. Версия php
2. Проверьте права на файл cache.db, пользователь php должен иметь права
3. проверьте , что в конфиге указан  правильно `'urlAPI' => "https://wiki.site.ru/api.php",`, ну и что на него можно зайти. Скрипт работает только с открытым апи

**Comment by Valirius** [comment]
Да, удалил файл и он создал его правильно. Похоже проблема была в том, что он его создал, когда была проблема с sqllite3 (его вообще не стояло по сути). И в пути к апи.пхп был лишний "$server ."

Всё, разобрался. Спасибо тебе!
